# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"A\n\x13GetUserByIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"H\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0c\n\x04role\x18\x03 \x01(\t2\x9b\x01\n\x0bUserService\x12\x42\n\x0bGetUserById\x12\x18.user.GetUserByIdRequest\x1a\x19.user.GetUserByIdResponse\x12H\n\rValidateToken\x12\x1a.user.ValidateTokenRequest\x1a\x1b.user.ValidateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERBYIDREQUEST']._serialized_start=20
  _globals['_GETUSERBYIDREQUEST']._serialized_end=52
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=54
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=119
  _globals['_VALIDATETOKENREQUEST']._serialized_start=121
  _globals['_VALIDATETOKENREQUEST']._serialized_end=158
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=160
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=232
  _globals['_USERSERVICE']._serialized_start=235
  _globals['_USERSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
